spring:
  application:
    name: minishop-frontend
  datasource:
    url: jdbc:mysql:///minishop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
