spring:
  application:
    name: minishop-provider
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql:///minishop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      #url: jdbc:mysql://192.168.1.247:3306/minishop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource

      #druid 配置
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
  #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  ## 配置activemq
  activemq:
    #broker-url: tcp://192.168.1.247:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 20
    #开启对象传输白名单
    packages:
      trust-all: true
    broker-url: tcp://192.168.0.103:61616

  thymeleaf:
      cache: false

  #连接redis
  redis:
    #host: 192.168.1.247
    host: 192.168.0.103
    timeout: 1s   #redis连接超时1s
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
        max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 3600s     #缓存时效1小时
      cache-null-values: false #不缓存空值


#配置mybatis相关文件
mybatis:
  #mybatis全局配置文件
  #config-location: classpath:mybatis/mybatis-config.xml
  #mapper文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #开启二级缓存
    cache-enabled: true
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #延迟加载启动
    lazy-loading-enabled: true
    #积极的懒加载，false的话按需加载，默认是true
    aggressive-lazy-loading: false

eureka:
  instance:
    prefer-ip-address: true
  client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

server:
  port: 8010


