spring:
  application:
    name: minishop-elasticsearch
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.0.103:9300
      #cluster-nodes: 192.168.1.247:9300
  ## 配置activemq
  activemq:
    #broker-url: tcp://192.168.1.247:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 20
    #开启对象传输白名单
    packages:
      trust-all: true
    broker-url: tcp://192.168.0.103:61616


eureka:
  instance:
    prefer-ip-address: true
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8060
